// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzFN2urJIkl77iIKAfvJvLot9Wy18hYo',
    appId: '1:223287264957:web:83497d7d1b9ade371319d4',
    messagingSenderId: '223287264957',
    projectId: 'signup-5b87c',
    authDomain: 'signup-5b87c.firebaseapp.com',
    storageBucket: 'signup-5b87c.appspot.com',
    measurementId: 'G-FE76594NTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmf39ygECt1y4kNboXUNrhEc-mqPYoxpQ',
    appId: '1:223287264957:android:1cbff79ed68a1ba71319d4',
    messagingSenderId: '223287264957',
    projectId: 'signup-5b87c',
    storageBucket: 'signup-5b87c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszOrLJ66ot60dV0JJF5S0r9OvWDSPNNA',
    appId: '1:223287264957:ios:11901ac71ca224531319d4',
    messagingSenderId: '223287264957',
    projectId: 'signup-5b87c',
    storageBucket: 'signup-5b87c.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDszOrLJ66ot60dV0JJF5S0r9OvWDSPNNA',
    appId: '1:223287264957:ios:11901ac71ca224531319d4',
    messagingSenderId: '223287264957',
    projectId: 'signup-5b87c',
    storageBucket: 'signup-5b87c.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );
}
